'use client';

import React, { useState, useRef, useEffect } from 'react';
import {
  Network, Cpu, Zap, Radio, Send, Sparkles, RefreshCw, Terminal,
  Sliders, ShieldCheck, Download, Code2, Film, Image as ImageIcon,
  Layers, Play, AlertCircle, CheckCircle, FileText, Square
} from 'lucide-react';
import { useOmniWebSocket } from '../hooks/useOmniWebSocket';
import { routePrompt, classifyPrompt } from '../lib/api';
import MetricsCard from '../components/MetricsCard';
import ProviderSelector from '../components/ProviderSelector';
import TelemetryBadge from '../components/TelemetryBadge';
import CodeMarkdownCard from '../components/CodeMarkdownCard';
import MediaPreviewCard from '../components/MediaPreviewCard';
import TaskStatusStepper from '../components/TaskStatusStepper';

// Quick prompt presets to showcase multi-type dynamic routing
const PROMPT_PRESETS = [
  {
    label: '💻 Code Generation',
    prompt: 'Write a Python function to implement a binary search tree with insertion and traversal methods.',
    taskType: 'CODE'
  },
  {
    label: '🎨 Image Synthesis',
    prompt: 'Generate a photorealistic image of a futuristic neon cybernetic dragon perched on a skyscraper at dusk.',
    taskType: 'IMAGE_GENERATION'
  },
  {
    label: '📐 Math Derivation',
    prompt: 'Calculate the definite integral of f(x) = x^3 + 2x^2 - 5x + 3 from x = 0 to 4.',
    taskType: 'MATH'
  },
  {
    label: '🎬 Generative Video',
    prompt: 'Create a cinematic video of glowing ocean waves crashing on a black sand beach under moonlight.',
    taskType: 'VIDEO_GENERATION'
  }
];

export default function WorkspaceDashboard() {
  const [routingMode, setRoutingMode] = useState('auto'); // 'auto' (Intent Router) | 'manual'
  const [selectedProvider, setSelectedProvider] = useState('gemini');
  const [selectedModel, setSelectedModel] = useState('gemini-1.5-flash');
  const [temperature, setTemperature] = useState(0.7);
  const [streaming, setStreaming] = useState(true);
  const [prompt, setPrompt] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Pre-populated messages depicting initial prompt & BinarySearchTree class implementation
  const [messages, setMessages] = useState([
    {
      id: 'init-msg-user',
      sender: 'user',
      text: 'Write a Python function to implement a binary search tree with insertion and traversal methods.',
      timestamp: '10:42:15 AM'
    },
    {
      id: 'init-msg-assistant',
      sender: 'assistant',
      loading: false,
      output: `\`\`\`python
# OmniBridge Gateway — Auto-routed to gemini/gemini-1.5-flash
# Requirement: Write a Python function to implement a binary search tree with insertion and traversal methods.

class TreeNode:
    """Node structure for a Binary Search Tree."""
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None

class BinarySearchTree:
    """Binary Search Tree implementation with insertion and traversal methods."""
    def __init__(self):
        self.root = None

    def insert(self, key):
        """Insert a new key into the BST."""
        if self.root is None:
            self.root = TreeNode(key)
        else:
            self._insert_recursive(self.root, key)

    def _insert_recursive(self, current, key):
        if key < current.key:
            if current.left is None:
                current.left = TreeNode(key)
            else:
                self._insert_recursive(current.left, key)
        elif key > current.key:
            if current.right is None:
                current.right = TreeNode(key)
            else:
                self._insert_recursive(current.right, key)

    def inorder(self, root):
        """In-order tree traversal returning sorted keys."""
        res = []
        if root:
            res.extend(self.inorder(root.left))
            res.append(root.key)
            res.extend(self.inorder(root.right))
        return res

# Example execution
if __name__ == '__main__':
    bst = BinarySearchTree()
    for val in [50, 30, 20, 40, 70, 60, 80]:
        bst.insert(val)
    print("In-order BST Traversal:", bst.inorder(bst.root))
\`\`\`

*This code was generated by OmniBridge's Code Intent Router pipeline.*`,
      telemetry: {
        taskType: 'CODE',
        targetModel: 'gemini-1.5-flash',
        targetProvider: 'gemini',
        actualLatencyMs: 124,
        confidence: 0.98,
        classificationMethod: 'ast-semantic'
      },
      timestamp: '10:42:16 AM'
    }
  ]);

  // Telemetry metric state
  const [metrics, setMetrics] = useState({
    status: 'OPERATIONAL',
    provider: 'Gemini 1.5',
    model: 'gemini-1.5-flash',
    latency: 24,
    tokens: 420
  });

  // Custom WebSocket Hook
  const {
    status: wsStatus,
    activeTaskMap,
    eventLogs,
    streamingContent,
    isStreaming,
    submitAsyncTask,
    startTokenStream,
    subscribeToTask,
    stopStream,
    clearLogs
  } = useOmniWebSocket();

  const chatEndRef = useRef(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, streamingContent, activeTaskMap]);

  // Stop Execution action handler
  const handleStopExecution = () => {
    setIsSubmitting(false);
    stopStream();
    setMessages((prev) =>
      prev.map((msg) =>
        msg.loading
          ? {
              ...msg,
              loading: false,
              error: 'Execution stopped by user.'
            }
          : msg
      )
    );
  };

  // Dispatch prompt submission
  const handleSubmit = async (e) => {
    if (e) e.preventDefault();
    if (!prompt.trim() || isSubmitting) return;

    const currentPrompt = prompt;
    setPrompt('');
    setIsSubmitting(true);

    const messageId = Math.random().toString(36).substring(2, 9);
    const userMsg = { id: messageId, sender: 'user', text: currentPrompt, timestamp: new Date().toLocaleTimeString() };
    
    setMessages((prev) => [...prev, userMsg]);

    if (routingMode === 'auto') {
      // Step 1: Pre-classify intent for instant UI telemetry feedback
      const cls = await classifyPrompt(currentPrompt);
      
      const assistantMsgId = Math.random().toString(36).substring(2, 9);
      const initialAssistantMsg = {
        id: assistantMsgId,
        sender: 'assistant',
        loading: true,
        telemetry: {
          taskType: cls.taskType || 'TEXT',
          targetModel: cls.recommendedModel || 'gemini-1.5-flash',
          targetProvider: cls.recommendedProvider || 'gemini',
          confidence: cls.confidence || 0.95,
          classificationMethod: cls.classificationMethod || 'keyword',
          estimatedLatency: cls.estimatedLatency || 800,
          costTier: cls.costTier || 'low',
          capability: cls.capability || ''
        },
        timestamp: new Date().toLocaleTimeString()
      };

      setMessages((prev) => [...prev, initialAssistantMsg]);

      // Handle Image / Video async tasks vs Text/Code tasks
      const isAsyncMedia = cls.taskType === 'IMAGE_GENERATION' || cls.taskType === 'VIDEO_GENERATION';

      if (isAsyncMedia && wsStatus === 'READY') {
        // Dispatch via WebSocket Task Pipeline for real-time stepper updates
        submitAsyncTask({ prompt: currentPrompt, temperature, outputFormat: 'json' });
        setIsSubmitting(false);
      } else {
        // Dispatch via REST Intent Router pipeline
        const start = Date.now();
        const res = await routePrompt({ prompt: currentPrompt, temperature });
        const latencyMs = Date.now() - start;

        setIsSubmitting(false);

        if (res.success) {
          setMessages((prev) =>
            prev.map((msg) =>
              msg.id === assistantMsgId
                ? {
                    ...msg,
                    loading: false,
                    output: res.output,
                    telemetry: {
                      ...msg.telemetry,
                      taskType: res.taskType,
                      targetModel: res.targetModel,
                      targetProvider: res.targetProvider,
                      actualLatencyMs: res.actualLatencyMs || latencyMs,
                      confidence: res.confidence,
                      classificationMethod: res.classificationMethod
                    },
                    imageUrl: res.imageUrl,
                    taskId: res.taskId
                  }
                : msg
            )
          );

          setMetrics((prev) => ({
            ...prev,
            provider: res.targetProvider,
            model: res.targetModel,
            latency: res.actualLatencyMs || latencyMs
          }));
        } else {
          setMessages((prev) =>
            prev.map((msg) =>
              msg.id === assistantMsgId
                ? {
                    ...msg,
                    loading: false,
                    error: res.error || 'Router dispatch failed'
                  }
                : msg
            )
          );
        }
      }
    } else {
      // Manual provider mode
      if (streaming && wsStatus === 'READY') {
        startTokenStream({ prompt: currentPrompt, provider: selectedProvider, model: selectedModel, temperature, useRouter: false });
        setIsSubmitting(false);
      } else {
        // Sync REST completion fallback
        const start = Date.now();
        const { generateCompletion } = await import('../lib/api');
        const res = await generateCompletion({ provider: selectedProvider, model: selectedModel, prompt: currentPrompt, temperature });
        const latencyMs = Date.now() - start;

        setIsSubmitting(false);

        const assistantMsg = {
          id: Math.random().toString(36).substring(2, 9),
          sender: 'assistant',
          loading: false,
          output: res.data?.output || 'No output received',
          telemetry: {
            taskType: 'TEXT',
            targetModel: selectedModel,
            targetProvider: selectedProvider,
            actualLatencyMs: latencyMs
          },
          timestamp: new Date().toLocaleTimeString()
        };

        setMessages((prev) => [...prev, assistantMsg]);
      }
    }
  };

  return (
    <div className="h-screen overflow-hidden flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 space-y-4">
      {/* 1. Header & Address Bar (Topmost) */}
      <header className="flex-none flex flex-wrap items-center justify-between gap-4 pb-3 border-b border-gray-800">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-gradient-to-tr from-sky-500 via-blue-600 to-indigo-600 text-white shadow-lg shadow-sky-500/20">
            <Network className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-lg font-bold tracking-tight text-white flex items-center gap-2 font-sans">
              OmniBridge <span className="text-xs px-2 py-0.5 rounded bg-sky-500/10 text-sky-400 border border-sky-500/20 font-mono font-normal">v1.0 Engine</span>
            </h1>
            <p className="text-[11px] text-gray-400">
              Intelligent Multi-Provider AI Orchestration, Intent Classifier & Real-Time Gateway
            </p>
          </div>
        </div>

        {/* Status Indicators */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1 rounded-lg bg-dark-surface border border-gray-800 text-xs font-mono">
            <span className="flex h-2 w-2 relative">
              <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${wsStatus === 'READY' ? 'bg-emerald-400' : 'bg-amber-400'}`} />
              <span className={`relative inline-flex rounded-full h-2 w-2 ${wsStatus === 'READY' ? 'bg-emerald-500' : 'bg-amber-500'}`} />
            </span>
            <span className="text-gray-300">WS Pipeline: {wsStatus}</span>
          </div>
        </div>
      </header>

      {/* 2. Orchestration & Control Bar (Full-Width, Directly Underneath Header) */}
      <div className="flex-none space-y-2 pb-2 border-b border-gray-800/80">
        {/* Orchestration Mode Switcher */}
        <div className="glass-panel rounded-xl p-3 border border-gray-800 flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 text-xs font-semibold text-gray-200 uppercase tracking-wider font-mono">
              <Sliders className="w-4 h-4 text-sky-400" />
              <span>Orchestration Mode:</span>
            </div>

            <div className="bg-dark-base p-1 rounded-lg border border-gray-800 flex items-center gap-1">
              <button
                onClick={() => setRoutingMode('auto')}
                className={`px-3 py-1 rounded-md text-xs font-medium transition-all flex items-center gap-1.5 ${
                  routingMode === 'auto'
                    ? 'bg-sky-600 text-white shadow-md shadow-sky-600/30'
                    : 'text-gray-400 hover:text-gray-200'
                }`}
              >
                <Sparkles className="w-3.5 h-3.5" />
                <span>Auto Intent Router</span>
              </button>

              <button
                onClick={() => setRoutingMode('manual')}
                className={`px-3 py-1 rounded-md text-xs font-medium transition-all flex items-center gap-1.5 ${
                  routingMode === 'manual'
                    ? 'bg-purple-600 text-white shadow-md shadow-purple-600/30'
                    : 'text-gray-400 hover:text-gray-200'
                }`}
              >
                <Layers className="w-3.5 h-3.5" />
                <span>Manual Provider Override</span>
              </button>
            </div>
          </div>

          <div className="text-xs text-gray-400 font-mono">
            {routingMode === 'auto'
              ? '⚡ Automatic Semantic Classifier + Cost Rule Matrix Active'
              : '⚙️ Fixed Provider Routing Mode Active'}
          </div>
        </div>

        {/* Manual Provider Selector (shown only in manual mode) */}
        {routingMode === 'manual' && (
          <ProviderSelector
            selectedProvider={selectedProvider}
            setSelectedProvider={setSelectedProvider}
            selectedModel={selectedModel}
            setSelectedModel={setSelectedModel}
            temperature={temperature}
            setTemperature={setTemperature}
            streaming={streaming}
            setStreaming={setStreaming}
          />
        )}

        {/* Action Preset Chips Bar */}
        <div className="flex items-center gap-2 overflow-x-auto pb-0.5 scrollbar-none">
          <span className="text-xs text-gray-500 font-mono shrink-0">Presets:</span>
          {PROMPT_PRESETS.map((preset, idx) => (
            <button
              key={idx}
              onClick={() => setPrompt(preset.prompt)}
              className="shrink-0 text-xs px-3 py-1 rounded-lg bg-dark-surface/80 hover:bg-dark-surface border border-gray-800 text-gray-300 transition-colors flex items-center gap-1.5 font-mono"
            >
              <span>{preset.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* 3. Main Dashboard Body Layout: Fixed Height Viewport Constraint with Internal Scroll */}
      <div className="flex-1 min-h-0 grid grid-cols-1 lg:grid-cols-3 gap-4 overflow-hidden">
        
        {/* Left Sidebar Column */}
        <div className="lg:col-span-1 flex flex-col h-full min-h-0 overflow-hidden space-y-3">
          {/* Top Section of Sidebar: 4 KPI / Telemetry Stat Cards */}
          <div className="flex-none">
            <MetricsCard metrics={metrics} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-2.5" />
          </div>

          {/* Bottom Section of Sidebar: Live WebSocket Tasks Panel */}
          <div className="glass-panel rounded-xl p-3 border border-gray-800 flex flex-col flex-1 min-h-0 overflow-hidden">
            <div className="flex-none flex items-center justify-between pb-2 border-b border-gray-800 mb-2">
              <div className="flex items-center gap-2">
                <Radio className="w-4 h-4 text-purple-400 animate-pulse" />
                <h3 className="text-xs font-semibold uppercase text-gray-300 tracking-wider font-mono">
                  Live WebSocket Tasks
                </h3>
              </div>
              <button
                onClick={clearLogs}
                className="text-[11px] text-gray-500 hover:text-gray-300 font-mono transition-colors"
              >
                Clear
              </button>
            </div>

            {/* Task Stepper Status Cards & Log Container */}
            <div className="flex-1 overflow-y-auto space-y-3 pr-1 min-h-0">
              {Object.keys(activeTaskMap).length === 0 ? (
                <div className="text-center py-6 text-xs font-mono text-gray-600 italic">
                  No active WebSocket background tasks.
                </div>
              ) : (
                Object.values(activeTaskMap).map((task) => (
                  <TaskStatusStepper
                    key={task.id}
                    status={task.status}
                    progress={task.progress}
                    message={task.message}
                  />
                ))
              )}

              {/* Live Event Stream Logger */}
              <div className="pt-2 border-t border-gray-800 space-y-2">
                <div className="text-[11px] font-mono text-gray-400 uppercase font-semibold">
                  Raw Gateway Packet Stream
                </div>
                <div className="space-y-1.5 font-mono text-[11px] max-h-[140px] overflow-y-auto pr-1">
                  {eventLogs.length === 0 ? (
                    <span className="text-gray-600 italic">Listening on ws://localhost:5000...</span>
                  ) : (
                    eventLogs.map((log) => (
                      <div
                        key={log.id}
                        className="p-1.5 rounded bg-dark-base border border-white/5 flex flex-col gap-0.5"
                      >
                        <div className="flex items-center justify-between text-[9px]">
                          <span
                            className={
                              log.level === 'ERROR'
                                ? 'text-red-400 font-bold'
                                : log.level === 'SUCCESS'
                                ? 'text-emerald-400 font-bold'
                                : 'text-sky-400'
                            }
                          >
                            [{log.level}]
                          </span>
                          <span className="text-gray-500">{log.timestamp}</span>
                        </div>
                        <span className="text-gray-300 text-[10px] break-all">{log.message}</span>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* 4. Main Execution Area (Right Side): OmniBridge Response Terminal */}
        <div className="lg:col-span-2 flex flex-col h-full min-h-0 overflow-hidden">
          <div className="glass-panel rounded-xl border border-gray-800 flex flex-col h-full min-h-0 overflow-hidden">
            {/* Terminal Header bar */}
            <div className="flex-none bg-dark-surface/80 px-4 py-2.5 border-b border-gray-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Terminal className="w-4 h-4 text-sky-400" />
                <span className="text-xs font-mono text-gray-300 font-semibold">
                  OmniBridge Response Terminal
                </span>
              </div>
              <span className="text-[11px] font-mono text-gray-400">
                {messages.length} message(s)
              </span>
            </div>

            {/* Chat Message Stream - Internal Scroll Container */}
            <div className="flex-1 min-h-0 p-4 overflow-y-auto space-y-4 bg-dark-base/90">
              {messages.length === 0 && !isStreaming ? (
                <div className="h-full flex flex-col items-center justify-center text-center p-8 space-y-3">
                  <div className="p-4 rounded-full bg-sky-500/10 border border-sky-500/20 text-sky-400">
                    <Sparkles className="w-8 h-8" />
                  </div>
                  <h3 className="text-sm font-semibold text-gray-200">
                    Ready for Multi-Provider AI Orchestration
                  </h3>
                  <p className="text-xs text-gray-400 max-w-md">
                    Enter a prompt or select a preset. OmniBridge will classify your intent and auto-route to Gemini, OpenAI, Together AI (FLUX), or Runway ML.
                  </p>
                </div>
              ) : (
                messages.map((msg) => (
                  <div key={msg.id} className="space-y-2">
                    {msg.sender === 'user' ? (
                      /* User Message Bubble */
                      <div className="flex justify-end">
                        <div className="bg-sky-600/20 border border-sky-500/30 text-sky-100 rounded-xl px-4 py-3 max-w-xl text-sm font-sans">
                          {msg.text}
                          <div className="text-[10px] font-mono text-sky-400/70 text-right mt-1">
                            {msg.timestamp}
                          </div>
                        </div>
                      </div>
                    ) : (
                      /* Assistant Response Card */
                      <div className="bg-dark-surface/70 border border-gray-800 rounded-xl p-4 space-y-3">
                        {/* Render Telemetry Badge */}
                        {msg.telemetry && <TelemetryBadge telemetry={msg.telemetry} />}

                        {/* Render Output based on Task Type */}
                        {msg.loading ? (
                          <div className="flex items-center gap-2 text-xs font-mono text-sky-400 py-4">
                            <RefreshCw className="w-4 h-4 animate-spin" />
                            <span>Routing intent & generating response from optimal API provider...</span>
                          </div>
                        ) : msg.error ? (
                          <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-400 rounded-lg text-xs font-mono">
                            ⚠️ {msg.error}
                          </div>
                        ) : msg.telemetry?.taskType === 'IMAGE_GENERATION' || msg.telemetry?.taskType === 'VIDEO_GENERATION' ? (
                          <MediaPreviewCard
                            taskType={msg.telemetry.taskType}
                            output={msg.output}
                            imageUrl={msg.imageUrl}
                            taskId={msg.taskId}
                            provider={msg.telemetry.targetProvider}
                            model={msg.telemetry.targetModel}
                          />
                        ) : (
                          <CodeMarkdownCard
                            rawOutput={msg.output}
                            taskId={msg.taskId}
                            language={msg.telemetry?.language}
                            outputType={msg.telemetry?.outputType}
                          />
                        )}
                      </div>
                    )}
                  </div>
                ))
              )}

              {/* Streaming Content Token Render */}
              {isStreaming && (
                <div className="bg-dark-surface/70 border border-gray-800 rounded-xl p-4 space-y-2">
                  <div className="flex items-center gap-2 text-xs font-mono text-sky-400">
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    <span>Real-Time WebSocket Stream Token Feed</span>
                  </div>
                  <pre className="p-4 font-mono text-xs text-gray-200 overflow-x-auto max-h-[350px] overflow-y-auto bg-[#06090E] rounded-lg typing-cursor">
                    {streamingContent}
                  </pre>
                </div>
              )}

              <div ref={chatEndRef} />
            </div>

            {/* Input Form with Stop Execution Support */}
            <form onSubmit={handleSubmit} className="flex-none p-3 bg-dark-surface/50 border-t border-gray-800">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder={
                    routingMode === 'auto'
                      ? 'Type prompt (Auto-classified: Text, Math, Code, Image, Video)...'
                      : `Ask ${selectedProvider} (${selectedModel})...`
                  }
                  className="flex-1 bg-dark-base border border-gray-800 rounded-lg px-4 py-2.5 text-sm text-gray-100 placeholder-gray-500 focus:outline-none focus:border-sky-500 font-mono"
                />
                {isSubmitting || isStreaming ? (
                  <button
                    type="button"
                    onClick={handleStopExecution}
                    className="bg-red-600/20 hover:bg-red-600/30 border border-red-500/50 text-red-400 font-medium px-4 py-2.5 rounded-lg flex items-center gap-2 text-sm transition-all duration-200 shadow-lg shadow-red-600/10 animate-pulse shrink-0"
                  >
                    <Square className="w-3.5 h-3.5 fill-red-400" />
                    <span>Stop Execution</span>
                  </button>
                ) : (
                  <button
                    type="submit"
                    disabled={!prompt.trim()}
                    className="bg-sky-600 hover:bg-sky-500 disabled:opacity-50 text-white font-medium px-5 py-2.5 rounded-lg flex items-center gap-2 text-sm transition-all duration-200 shadow-lg shadow-sky-600/20 shrink-0"
                  >
                    <Send className="w-4 h-4" />
                    <span>Dispatch</span>
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
